#!/usr/bin/env bash

---
layout: post
title: Quibit and Gel Alexa and Ana
date: '2019-12-02'
categories: Processing
tags: DNA RNA Quibit Gel
---
## 10 RNA    10 DNA
## Extraction date: 20191125

## Buffer: (12.2)(199)=2,427.8
## Reagent: 10+2+.2=22.2
## DNA
    S1: 34.29
    S2: 16151.99

## RNA
    S1: 49.15
    S2: 924.45

| Extraction #  | DNA 1  | DNA 2 | RNA 1  | RNA 2  |
|---|---|---|---|---|
|  595 | 36.4  | 36.2  | 19.4  | 19.3  |
|  596 | 17.7  | 17.7  | 12.6  | 12.7  |
|  597 | 23.0  | 23.0  | 9.9   | 10.0  |
|  598 | 13.3  | 13.3  | 6.0   | 6.04  |
|  599 | 18.7  | 18.7  | 10.4  | 10.5  |
|  560 | 12.4  | 12.3  | 7.94  | 8.02  |
|  561 | 15.2  | 15.1  | 12.1  | 12.2  |
|  562 | 8.1   | 8.08  | 7.72  | 7.80  |
|  563 | 34.4  | 34.3  | 30.6  | 30.8  |
|  564 | 23.4  | 23.2  | 10.1  | 10.1  |

*602 RNA sample lost cap in mini centrifuge

Gel Map:  L 595=>604git


 Ask user for input
echo "Enter title:"
read PHRASE
echo "You entered $PHRASE"

echo "Enter categories: (Analysis, Goals, Processing, Protocols)"
read PHRASE2
echo "You entered $PHRASE2"

echo "Enter tags: include []"
read PHRASE3
echo "You entered $PHRASE3"

# Remove spaces from PHRASE and replace with hyphens
FORMATTED_PHRASE="$(echo -ne "${PHRASE}" | tr [:space:] '-')"

# Save new filename using POST_DATE and FORMATTED_PHRASE variables.
NEW_MD_FILE="$(echo -n "${POST_DATE}"-"${FORMATTED_PHRASE}")".md


# Prints formatted Jekyll header utilizing POST_DATE and user-entered PHRASE.
# Writes contents to NEW_MD_FILE
printf "%s\n%s\n%s%s\n%s'%s'\n%s%s\n%s%s\n%s%s\n" "$MD_LINE" "$LAYOUT" "$TITLE" "$PHRASE" "$DATE_LINE" "$POST_DATE" "$CATEGORIES" "$PHRASE2" "$TAGS" "$PHRASE3" "$MD_LINE" >> \
"$NEW_MD_FILE"

# Opens NEW_MD_FILE in nano text editor for editing.
nano "$NEW_MD_FILE"


# Use git to stage, commit, and push NEW_MD_FILE to GitHub
git add "$NEW_MD_FILE"
git commit -m "created new post: $NEW_MD_FILE"
git push origin master
